version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Maps port 5000 on the host to port 5000 in the backend container

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Maps port 3000 on the host to port 3000 in the frontend container
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000  # Set environment variable to point frontend to backend
